### ISSUE TITLE
Feature suggestion: Auto dismount when you talk with a flight master NPC

### ISSUE THREAD

**Issue by Nillx** [leatrix/leatrix-plus-bcc#16]
Currently you have to double click on the fly path destination dot. One click to dismount you and a second click to actually send you flying.

I was thinking of an option that auto dismounts you when you speak with a Flight Master NPC (i even saw addons that do that).

**Comment by leatrix** [comment]
Thanks for your suggestion.  Added to 2.5.38.alpha.3.

From the change log:
2.5.38.alpha.3 - 27th May 2021
- The 'Dismount automatically' option ('System') will now dismount you when you talk to a flight master so that you are already dismounted and ready to go the moment you select a flight destination.

**Comment by Nillx** [comment]
Thanks it works great. 

"The 'Dismount automatically' option ('System') will no longer dismount you if you are out of range of your target." change got reverted tho, i get dismounted when i press any button now.

**Comment by leatrix** [comment]
Are you sure it's LTP that's dismounting you and not the game?

The dismount automatically option works by dismounting you when any of the following errors occur:

- **Not enough rage**
LTP will dismount you if you cast a spell but don't have enough rage.
- **Not enough mana**
LTP will dismount you if you cast a spell but don't have enough mana.
- **Not enough energy**
LTP will dismount you if you cast a spell but don't have enough energy.
- **Can't do that while moving**
LTP will dismount you if you cast a spell which has a cast time but you are moving.
- **You are already mounted! Dismount first.**
LTP will dismount you if you click a flight destination on the flight map.

And now it will dismount when the flight map is opened too.  That's it.

Everything else is handled by the default UI.  Even without addons, the game will now dismount you if you cast a spell which would succeed (i.e. if you are in range and have enough rage/mana/energy to cast the spell).

**Comment by Nillx** [comment]
All good then, its working fine. I was testing it with spamming Shadow Bolt while moving, spamming other spells does not dismount me.

**Comment by leatrix** [comment]
It's not perfect.  For example, you will be dismounted by LTP if you cast an offensive spell that you don't have enough mana to cast and you don't have a target - it all depends on the errors that the game shows.  If the game reports 'Not enough mana', you will be dismounted.  But adding a check to make sure you have a target wouldn't work because some spells don't require targets.

**Comment by leatrix** [comment]
In 2.5.38.alpha.4, the dismount option now has a configuration panel so you can set which dismount rules you want to use.

**Comment by Nillx** [comment]
Thanks thats a nice addition.
