### ISSUE TITLE
Faster auto loot - Looting with other players frequently shows loot that was picked up

### ISSUE THREAD

**Issue by boktai1000** [leatrix/leatrix-plus-bcc#38]
Version: Leatrix Plus BCC 2.5.42

Issue: With Faster auto loot enabled, frequently I encounter issues when looting mobs at or near the same time as other players showing the loot window on screen with loot that has already been picked up, and erroring/not letting you pick it up.

Frequently this happens with Silver on a mobs corpse, as it's something that consistently drops with mobs, but can and has happened with other item types.

I'm not sure if there are any additional checks that can / should be in place for this, as it sort of catches you off guard and may do the opposite effect of Faster looting by having you trying to manually try to loot but to no avail.

There is another Addon with a similar feature to yours called Speedy AutoLoot I do not believe it has the same issue, but haven't replicated it - maybe the approach this addon is taking may be worth looking into, regardless I thought I would at least mention it for reference. My preference would be use Leatrix built-in for all possible needs, and just wanted to bring this issue to attention. https://www.curseforge.com/wow/addons/speedyautoloot

**Comment by leatrix** [comment]
What loot rules are you using (free for all, group loot, master looter, etc)?
What errors are you seeing?

**Comment by boktai1000** [comment]
Mostly this occurs with Free For All

I'll need to screenshot next time this happens / capture the error dialogue - but basically the loot window is open, showing loot there still, but it's not.

**Comment by leatrix** [comment]
Does it ever happen when you are not grouped?

**Comment by boktai1000** [comment]
I want to say it doesn't - this is almost exclusively a problem when looting a corpse at nearly the same time as another grouped member in my experience (the player I usually compete for loot with is using that Speedy AutoLoot addon too - so it's kind of like which Addon is faster in that regard too - with FFA loot enabled - but more often than not, I'm left with a "fake loot window" that I'm describing in this issue).

**Comment by boktai1000** [comment]
I was using 2.5.43.alpha.2 last night (I have not used 2.5.43.alpha.3) and was still experiencing the issue last night. It's sort of hard to capture in Screenshot format, but I did manage to grab a few screenshot sort of showcasing the issue

Loot has already been picked up - 4s 11c on the mob, but the chat window says my share of the loot is 2 silver, 5 copper. I can also confirm that in this case, clicking the silver did nothing - no error message, it was just stuck open until I moved
![asdf](https://user-images.githubusercontent.com/9054563/122941781-535bfa00-d33b-11eb-9032-24550714b5e7.PNG)

In this situation, I actually just had the loot window stuck open with no loot in it at all
![asdfasdf](https://user-images.githubusercontent.com/9054563/122941980-7ab2c700-d33b-11eb-8823-1b9c7826afcf.PNG)

This is was the same as the first screenshot, just another case I captured. You can see the silver on the mob, 9s 28c and my share of the loot has already been printed to the chat and the window is open and unable to be interacted with.
![asdfasdfasdf](https://user-images.githubusercontent.com/9054563/122942036-84d4c580-d33b-11eb-9907-1bad38bd9666.PNG)

**Comment by leatrix** [comment]
In 2.5.43.alpha.2 or higher... if you are grouped and the loot method is set to free for all, fast loot is only used if the item is not money.  If the item is money, fast loot is not used.

I was able to replicate the issue prior to 2.5.43.alpha.2.  When two grouped characters looted the same corpse at the same time, with loot method set to free for all, if the loot item was money, the loot window would remain open.  The fix in 2.5.43.alpha.2 resolved that for me.

Try with other addons disabled and I'll take another look at it too.  There are no changes to faster auto loot in 2.5.43.alpha.3.

**Comment by leatrix** [comment]
I tested it in open world with two characters on the same quest which required killing humanoids that dropped quest items.  Both characters looted the corpses at the same time and there were no issues at all.  Both characters were grouped with loot set to free for all.  Both characters using only LTP/LTM with 'Faster auto loot' enabled in LTP.

**Comment by boktai1000** [comment]
Hey sorry about the lack of replies! I've been busy and haven't had a good opportunity to test this under those circumstances with nothing else enabled. I do have multiple accounts, but I don't think I'd be fast enough to loot between them, so it may be a bit longer on my testing/attempted reproduction under those circumstances.

What I do have to report though is I've been running with the option disabled though the past week, and did not encounter the problem since disabling it (with latest version).

I'll follow up though once I have a chance to re-test, and possibly try to grab taint.log/etc if possible or whatever other information I can get.

**Comment by boktai1000** [comment]
Tested again today - with addons enabled I was able to reproduce it here

![image](https://user-images.githubusercontent.com/9054563/124343870-7f297c00-db94-11eb-8039-d0c74e618a89.png)


And then I disabled every single addon except for Leatrix Maps and Leatrix Plus and was able to reproduce it actually

![image](https://user-images.githubusercontent.com/9054563/124343916-c283ea80-db94-11eb-8716-674017d4187d.png)

The key to reproducing it is as follows - we attempted to loot the mob instantly / the second it dies. They were using Speedy AutoLoot, and I was using Leatrix Plus with the option for Fast Loot enabled. The only two addons I had enabled were Leatrix Maps and Plus.

Hope this helps - we tried to clear Stockades with a bunch of mobs and then do a count down and loot at the same time and never was able to pull it off. The only way we could is if we agreed to both attempt to loot the instant/second a mob died - and then during that time, we were able to pull this bug off and reproduce it.

Thanks!

**Comment by leatrix** [comment]
Tested in a two character group using free-for-all loot with ONLY SpeedyAutoLoot enabled (all other addons including LTP disabled).  Frequently when looting, one character would loot while the other would remain in the crouched position as if it were looting, but no loot was available.  So using SpeedyAutoLoot exclusively isn't any better.

I disabled SpeedyAutoLoot and the problem didn't occur.  I enabled it again and the problem came back - one character would remain in the crouched position indefinitely, trying to take loot that didn't exist.

The crouching problem showed regardless of when both characters looted the corpse but when they did, they both looted the same corpse within half a second of each other when the corpse was sparkling to both characters.  If there was a delay between the characters looting, the problem did't occur because one character had looted everything.

So because of this, the best I could probably do is to disable fast looting while you are in a group using free for all loot.

Blizzard have made a support ticket about a similar problem here:
https://us.battle.net/support/en/article/51912
It's not quite the same issue but it still involves the corpse making you think loot is available when actually there is no loot at all.  However, Blizzard say it's a feature, not a bug, because it accurately mimics how looting worked in TBC.

**Comment by boktai1000** [comment]
Just so that I understand, does the crouching problem happen with LTP as well? I imagine it does - but so I understand it:

- Speedy AutoLoot has the crouching problem, but doesn't have a loot window up
- LTP has the crouching problem, but also sometimes (or during that time) may have a "fake" loot window visible

If I understand this correctly, then I would say the way Speedy AutoLoot is handling it, albeit not perfect - is probably a "better" or least offensive of the two.

But that support ticket regarding the intended behavior or rather "feature" of the game, I would think failing or treating those events and "failing" in a similar manner as the intended behavior of the game might also be an ideal option, however that may be.

Definitely a very interesting support ticket - sort of surprising to me they have something so highly specific like that documented as the intended behavior.

Anyways I digress. My TL;DR though is it sort of feels like LTP has introduced a "new" bug on top of it though with the "fake loot present". Personally, I'd take Speedy AutoLoot's "imperfect" implementation of it with crouching, or just fail back to Blizzards own issues if it meant resolving the fake loot problem though.

Thanks for listening to my feedback :)

**Comment by leatrix** [comment]
Tested same as above test but with two characters using LTP 'Faster auto loot' (no other addons enabled).  No problems at all.  No extended crouching and no loot windows.  If possible, ask your friends to disable SpeedyAutoLoot and try LTP 'Faster auto loot' instead (so nobody in your group is using SpeedyAutoLoot) and see if that helps.  Ask them to double-check that SpeedyAutoLoot is definitely disabled before testing.

The problem with changing the code for LTP 'Faster auto loot' so that it works in a similar way to 'SpeedyAutoLoot' is that it would then introduce the extended crouching issue which isn't present (at least not in my tests) when everyone in the group uses LTP 'Faster auto loot'.

**Comment by boktai1000** [comment]
I'll try but I guess my question is - I won't ever really be able to predict what addons other users are running in the game world, and it sounds like unless I advocate for everyone to use LTP w/ Faster Auto Loot - I could potentially run into the issue?

And yeah, I'll do another test some time soon and report back
