### ISSUE TITLE
Don't see group/raid members

### ISSUE THREAD

**Issue by Molodiy** [leatrix/leatrix-plus-bcc#46]
When I first downloaded the addon, I still saw the participants. Now I don't see any. Only when I move around the map with the mouse does it show me the names of the players.
![WoWScrnShot_071421_175757](https://user-images.githubusercontent.com/87435452/125645476-393c8ccd-3da9-47ae-a753-9ed15ecf2fcb.jpg)
![WoWScrnShot_070521_165011](https://user-images.githubusercontent.com/87435452/125645528-6686d60d-5434-4503-acf9-07f760da8f31.jpg)

**Comment by leatrix** [comment]
This is Leatrix Plus for BCC issue tracker.
Leatrix Maps for BCC issue tracker is here:
https://github.com/leatrix/leatrix-maps-bcc/issues

To solve your issue, update Leatrix Maps and [keep it updated](https://download.curseforge.com/).  This issue was fixed 5 weeks ago.  Blizzard removed the icons from the game, that's why you don't see them.  So LTM was updated to work around the problem.

Note: You will need to restart your game client after installing the update (/reload is not enough) so the game can find the new icons.
