### ISSUE TITLE
Uber UI debuff issue

### ISSUE THREAD

**Issue by Dagga69** [leatrix/leatrix-plus-bcc#54]
Burning Crusade Classic

Hi, I was able to move buff but not debuff.

 I goes to Uber Ui.toc and change core\buffs.lua to ##core\buffs.lua .
 
 It work.
 
 My question is : Is there a definite way to make it work with Uber Ui ? I get a 01 error with the addon everytime I login, refresh or change zone.
 
 Curseforge Link of the addon ( Burning Crusade Classic ) : https://www.curseforge.com/wow/addons/uber-ui
 
 I like your addon, don't put too much attention with this issue of mine since it work already, I was just wondering if there was an easy way to fix that one error at every login/refresh/... .

**Comment by leatrix** [comment]
Moved your issue to the BCC tracker.

As well as commenting out core\buffs.lua in Uber UI.toc, you also need to comment out lines containing 'buffs' in core\general.lua (there are 3 lines, prefix them all with -- to comment them out).

It's not possible to manage Uber UI buff frame in Leatrix Plus because Uber UI has its own buff frame and unfortunately there is no setting in the configuration panel to disable it.  The best thing to do is to ask the author of Uber UI to add an option to toggle buff customisation so that other addons can be used to manage the buff frame instead.  It would be very easy to do and would save having to edit Uber UI code manually.

**Comment by leatrix** [comment]
Just linking this here because it's a very similar issue:
https://github.com/leatrix/leatrix-plus/issues/14

**Comment by Dagga69** [comment]
Thanks a lot, I don't the error message again and my debuff are moved as I wanted.
I'm gonna give the issue about buff frame to Uber UI.

![image](https://user-images.githubusercontent.com/88922272/129441895-2da88e9c-85ec-4784-8d0c-1ea84b7b052e.png)

![image](https://user-images.githubusercontent.com/88922272/129441871-8060241e-2e76-43bd-ac1b-f3d838f655ae.png)
