### ISSUE TITLE
Conflict Fasterloot

### ISSUE THREAD

**Issue by MrSigy** [leatrix/leatrix-plus-bcc#66]
Hello,

I've been having a issue for a while that is a bit annoying where the quick loot option of the addon is conflicted with another addon I use TSM (TradeSkillMaster).

In particular the /tsm destroy function for prospecting/disenchanting sometimes get stuck on destroying and unable to further progress into the list. I know this can be caused by either addon so I will also raise the issue on the TSM page.

I hope that this can be sorted in the future and I wanted to thank you for all that you have done.

**Comment by leatrix** [comment]
TSM relies on the loot frame when performing certain operations.  'Faster auto loot' bypasses the loot frame so that it can loot as fast as possible.

What if fast looting was temporarily disabled while the TSM destroy window is showing - would that help?  You would need to show me screenshots of frames that are showing when TSM breaks so that I can instruct LTP to not fast looting while those frames are showing.  I don't use TSM so I don't know what frames that would be.  Someone did report this issue before and told me that checking for open TSM frames wouldn't really solve the problem because some TSM operations don't show TSM frames - such as looting creatures.

In addition, TSM uses local frame names, not global ones.  So if there are any frames that you want LTP to check, you would need to ask the TSM author to give those frames global frame names so that they can be accessed from LTP.  For example, if you want LTP to not use fast looting while the TSM destroy window is showing, the TSM author would need to give that destroy window a global name so LTP (and other addons) can access it.

**Comment by leatrix** [comment]
Please try 2.5.86.alpha.8 and let me know how you go on.  TSM Destroy should now work with 'Faster auto loot' so you no longer need to disable 'Faster auto loot' to use TSM Destroy.  I only tested it briefly though since I don't use TSM.  But in my test, I was able to run through a dungeon with the TSM Destroy window open, fast loot everything and use TSM Destroy without issue.  There's no need to have the pointer over the destroy button or anything.

https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all

**Comment by alexey-detr** [comment]
I've just tested it, also quite briefly, and it works just fine, thank you! 👍 I'll close the related PR.
