### ISSUE TITLE
Class Portraits are causing extreme FPS drops inside arenas

### ISSUE THREAD

**Issue by Evolvee** [leatrix/leatrix-plus-bcc#7]
Class Portrait option is causing extreme FPS drops in arenas.

I tried 3 different ways on how to show Class Portraits of Target/Focus/ToT but all of them cause the same FPS drops. (Tried even 2.4.3 addons, classic vanilla addons and retail addons)

**Comment by leatrix** [comment]
What happens if you do arena with only Leatrix Plus enabled?

**Comment by Evolvee** [comment]
Tested just now with Letrix-only enabled. Same fps drops.

Tested in 2v2 skirm, I noticed that when 1 of the dead opponents left arena, fps went back to normal.

**Comment by leatrix** [comment]
If you disable target of target (Game Menu > Interface > Combat), does that fix the problem?

**Comment by leatrix** [comment]
After testing it with target of target enabled, the framerate dropped when targeting a player who had a target.  When the targeted player didn't have a target, or target of target was disabled, there was no framerate drop.  That said, the framerate never dropped below around 130 fps.  I usually play with framerate capped at 100fps (vsync disabled) so never see a drop.  Do you cap your framerate and what sort of drops are you seeing in framerates?

**Comment by Evolvee** [comment]
I am at stable 120fps since i use a vsync. Otherwise i would be around 180-200.

When the frame rate drops, its around 70-80 fps.

**Comment by leatrix** [comment]
Okay.  As I said, it's caused by the target of target frame.  Specifically, when you have the target of target frame showing, and your target has a target, the target of target frame updates many many times per second even without addons.  Each time it updates, the class portraits addon (doesn't matter which one) has to apply the class portrait texture and this is what causes the framerate drop.

All I can do about this is either remove the option entirely, or prevent the option from applying class portrait to the target of target frame only (possibly with an option to toggle target of target class portrait on/off) or add a warning to the tooltip about the fps drop when the target of target frame is showing and your target has a target.

**Comment by Evolvee** [comment]
This should be consulted with Blizzard imo as I am not aware of similar issues being present in older clients.

There should be basically no reason to update the ToT frame OnUpdate every frame.

I guess the best temp solution would be to just disable the ToT frame for class checks.

**Comment by leatrix** [comment]
Please try version 2.5.32 and let me know if there's any improvement.

**Comment by Evolvee** [comment]
Still the same fps drops.

**Comment by leatrix** [comment]
It can't be avoided.

If you run this:

`/run hooksecurefunc("UnitFramePortrait_Update", function(self) print(GetTime()) end)
`

... it will print the time in chat every time a unit portrait frame is refreshed.  If your target of target frame isn't showing, then it's not often at all.  But as soon as your target of target frame shows up (from targeting a player who is targeting something, or starting combat), you will see just how frequent the target of target frame is refreshed while it's showing.

I could add a setting to not show the target of target portrait but would that be useful?  I imagine for many people that use class icon portraits, seeing the target of target portrait is essential.

**Comment by Evolvee** [comment]
Im pretty sure most ppl will just turn it off if they see the feature causing their ingame performance go down by 50%.

I will try to ask other ppl meanwhile if there arent some possible walkarounds.
