### ISSUE TITLE
Issue with TBC

### ISSUE THREAD

**Issue by BGP0231** [leatrix/leatrix-plus-bcc#74]
I ve been having trouble using this addon with TBC everytime i open it my map fuction keeps dissaperaring, or with ur lastest on all of my addon icon dissapered off my mini map?

**Comment by leatrix** [comment]
The 'Enhance minimap' option ('Interface') was completely changed with lots of new features such as square minimap, auto-hide addon buttons and combine addon buttons.  In addition, the minimap is now movable (hold alt and drag it) and the scale slider now applies to the minimap directly rather than the entire cluster.  In the next update for BCC, you'll be able to resize it too (this is already live for Shadowlands).

You can change all the settings in the 'Enhance minimap' configuration panel.

The 'Enhance minimap' option is now like a standalone minimap replacement addon built into LTP.   So if you're running another minimap replacement addon, it's going to conflict with it and you'll need to either disable the minimap replacement addon or uncheck 'Enhance minimap'.

All changes to LTP and LTM are detailed in the change log.  In CurseForge App, you can click the Change Log tab on the addon page.  On the website, the Change Log is shown on the [Files](https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files) page.

**Comment by BGP0231** [comment]
TY it worked boss ty for all your help
