### ISSUE TITLE
Versions 2.5.75 and 2.5.78 broke MBB (minimap button bag)

### ISSUE THREAD

**Issue by too2fun** [leatrix/leatrix-plus-bcc#76]
going back to version 2.5.74 fixed the issue.

**Comment by leatrix** [comment]
'Enhance minimap' ('Interface') has had a huge redesign.  It's now a complete minimap replacement addon in itself with round or square minimap, rescale, resize, auto-hide addon buttons and even a replacement for MBB built right in.

So if you use 'Enhance minimap', disable MBB as well as any minimap replacement addons.  Go into the 'Enhance minimap' configuration panel.

If you want to use the MBB replacement, ensure that 'Combine addon buttons' is enabled and you'll want to enable 'Replace non-standard buttons' too.  After the reload, you can right-click the minimap to see your addon buttons in a neat button frame.

I prefer 'Combine addon buttons' to MBB because the button frame is smaller (button tooltips will be moved in the next update to LTP so they don't cover the buttons) and MBB uses an update script which runs 100 times a second permanently while it's enabled.  LTP doesn't have an update script.  It just draws the button frame when you right-click.

It's all included with LTP 'Enhance minimap' so no need for MBB anymore.
