### ISSUE TITLE
Incorrect flight time

### ISSUE THREAD

**Issue by Epsynus** [leatrix/leatrix-plus-bcc#81]
Flight details: Area 52 (0.58:0.27) to Shattrath (0.44:0.67) (Horde) took 224 seconds.  This flight's actual time of 224 seconds does not match the saved flight time of 262 seconds.

**Comment by leatrix** [comment]
Many thanks.  I will include this and any more that you send in the next alpha.

**Comment by axlroden** [comment]
I'm assuming you got most your flight times from inflight? otherwise I would import his :) 

Also here's my DB of times inflight didn't have.
`
InFlightDB = {
	["version"] = "classic",
	["global"] = {
		["Alliance"] = {
			["Marshal's Refuge"] = {
				["Ratchet"] = 351,
			},
			["Moonglade"] = {
				["Gadgetzan"] = 651,
				["Everlook"] = 119,
				["Talrendis Point"] = 280,
			},
			["Hellfire Peninsula"] = {
				["Honor Hold"] = 74,
			},
			["Cosmowrench"] = {
				["Area 52"] = 65,
			},
			["Thelsamar"] = {
				["Thorium Point"] = 82,
				["Morgan's Vigil"] = 171,
			},
			["Tanaris"] = {
				["Caverns of Time"] = 60,
			},
			["Allerian Stronghold"] = {
				["Shattrath"] = 75,
				["Telredor"] = 159,
			},
			["Wildhammer Stronghold"] = {
				["Allerian Stronghold"] = 101,
			},
			["Toshley's Station"] = {
				["Sylvanaar"] = 60,
			},
			["Feathermoon"] = {
				["Cenarion Hold"] = 153,
			},
			["Sanctum of the Stars"] = {
				["Wildhammer Stronghold"] = 42,
			},
			["The Exodar"] = {
				["Blood Watch"] = 77,
			},
			["Old Hillsbrad Foothills Entrance"] = {
				["Durnholde Keep"] = 88,
			},
			["Temple of Telhamat"] = {
				["Telredor"] = 81,
			},
			["Area 52"] = {
				["Shattrath"] = 262,
				["Wildhammer Stronghold"] = 415,
			},
			["Theramore"] = {
				["Astranaar"] = 370,
			},
			["Telaar"] = {
				["Allerian Stronghold"] = 122,
				["Orebor Harborage"] = 189,
			},
			["Ironforge"] = {
				["Nethergarde Keep"] = 338,
				["Aerie Peak"] = 240,
				["Menethil Harbor"] = 114,
				["Chillwind Camp"] = 258,
				["Southshore"] = 215,
			},
			["The Stormspire"] = {
				["Shattrath"] = 315,
			},
			["Rut'theran Village"] = {
				["Gadgetzan"] = 680,
				["Cenarion Hold"] = 708,
			},
			["Shattrath"] = {
				["Evergrove"] = 205,
				["Area 52"] = 236,
				["Telredor"] = 85,
				["Allerian Stronghold"] = 75,
				["Telaar"] = 89,
				["Wildhammer Stronghold"] = 153,
				["Toshley's Station"] = 153,
				["Orebor Harborage"] = 147,
				["Honor Hold"] = 111,
				["Cosmowrench"] = 398,
			},
			["Sylvanaar"] = {
				["Toshley's Station"] = 58,
			},
			["Nethergarde Keep"] = {
				["Booty Bay"] = 251,
				["Southshore"] = 528,
			},
			["Thorium Point"] = {
				["Thelsamar"] = 88,
			},
			["Auberdine"] = {
				["Everlook"] = 270,
			},
			["Southshore"] = {
				["Darkshire"] = 417,
			},
			["Stormwind"] = {
				["Thelsamar"] = 212,
				["Ironforge"] = 216,
				["Southshore"] = 388,
			},
			["Everlook"] = {
				["Astranaar"] = 317,
				["Rut'theran Village"] = 335,
			},
			["Rebel Camp"] = {
				["Booty Bay"] = 116,
			},
			["Honor Hold"] = {
				["Toshley's Station"] = 225,
				["Telredor"] = 157,
				["Shattrath"] = 120,
			},
			["Telredor"] = {
				["Orebor Harborage"] = 63,
				["Honor Hold"] = 208,
				["Shattrath"] = 97,
			},
		},
	},
	["upload"] = 1642354935,
	["profileKeys"] = {
		["Vandpytte - Firemaw"] = "Default",
		["Pytadin - Firemaw"] = "Default",
		["Pytte - Firemaw"] = "Default",
		["Tryllemand - Firemaw"] = "Default",
		["Pytte - Skullflame"] = "Default",
		["Fuzzly - Firemaw"] = "Default",
	},
	["dbinit"] = 1134,
	["profiles"] = {
		["Default"] = {
			["barcolor"] = {
				["g"] = 0,
				["r"] = 0.454901960784314,
			},
			["border"] = "None",
			["inline"] = true,
			["font"] = "Expressway",
		},
	},
}
`

**Comment by frapacino** [comment]
飞行信息: 沙塔斯，泰罗卡森林 (0.44:0.67) to 萨尔玛，地狱火半岛 (0.65:0.50) (Horde) took 150 秒.  这次飞行的真实耗时 150 耗时不匹配预设的飞行计时 131 秒.

**Comment by leatrix** [comment]
@frapacino Shattrath to Thrallmar (Horde) is already in the latest alpha for BCC.

**Comment by axlroden** [comment]
maybe think about making a lua parser, for flights not in, and people can submit, I'm sure github workflows could be helpful there. I'll be happy to look into it if you have an easy way for people to extract.

**Comment by leatrix** [comment]
For now, it's only BCC and Classic Era/SoM so there aren't that many incorrect/missing flight times left to update.  There's a flurry at the moment (via GitHub/CurseForge/Email) because the copy-friendly report window was only added very recently and the setting itself is still very new but it'll soon settle.  I also need to verify some flight times (i.e. the last flight time I received doesn't match what I see in the game).  I don't know whether I shall add the setting for Shadowlands yet.

**Comment by leatrix** [comment]
After checking the submitted flight times myself, 11 were correct but 8 didn't match the flight times that I got during my tests.  I'm not sure what to make of that unless the flights change depending on other factors.  I updated the 8 that didn't match with my own test times.

The submitted flight times that don't match my tests are:
Horde: The Stormspire to Garadar
Horde: Marshal's Refuge to Camp Mojache
Alliance: Nethergarde Keep to Southshore
Alliance: Refuge Pointe to Booty Bay
Alliance: Shattrath to Cosmowrench
Alliance: Evergrove to Honor Hold
Alliance: Telredor to Honor Hold
Alliance: Everlook to Astranaar

**Comment by Epsynus** [comment]
For what it's worth, I tested  Horde: The Stormspire to Garadar and the timer I have on version 2.5.82 is accurate (Technically it was off by about 0.2s but it didn't trigger the report incorrect time part).

When flying it flew over the following flight paths:
Stormspire -> Area 52 -> Mok'Nathal Village -> Swamprat post -> Shattrath -> Garadar.

But flying back it goes
Garadar -> Zabra'Jin -> Thunderlord Stronghold -> Area 52 -> The Stormspire.

So maybe time varies depending on what FPs your character has unlocked, so it takes a different route?

**Comment by Epsynus** [comment]
Speaking of, I just got another prompt!

Flight details: Shattrath (0.44:0.67) to Thrallmar (0.65:0.50) (Horde) took 150 seconds.  This flight's actual time of 150 seconds does not match the saved flight time of 131 seconds.

**Comment by leatrix** [comment]
Stormspire to Garadar in 2.5.82 is 359 seconds.  Someone reported a time of 372 seconds so it was adjusted.  But in the latest alpha it's back to 359 seconds since that's what I get in my test (and you).  Shattrath to Thrallmar is already updated in the latest alpha as that had been reported previously.

**Comment by leatrix** [comment]
> So maybe time varies depending on what FPs your character has unlocked, so it takes a different route?

Yes, so that will need to be added in.

**Comment by Epsynus** [comment]
Yeah noticed it had been updated so deleted that post, hoping you wouldn't catch it, haha.

Always something that gotta complicate it, can't ever just be simple, hopefully you can figure out the time differences and get a solution going.

Also new time for the database:
Flight details: Area 52 (0.58:0.27) to Altar of Sha'tar (0.81:0.77) (Horde) took 437 seconds.  This flight does not exist in the database.

**Comment by leatrix** [comment]
> Always something that gotta complicate it, can't ever just be simple, hopefully you can figure out the time differences and get a solution going

If not, the flight times will just have to be accurate as long as you know the connecting flight points.

**Comment by brclarke** [comment]
Figured I would add to this thread instead of opening another Issue, can do that if preferred.

Flight details: Shattrath (0.44:0.67) to Altar of Sha'tar (0.81:0.77) (Alliance) took 234 seconds.  This flight does not exist in the database.

**Comment by leatrix** [comment]
@brclarke Adding to this thread is fine.  That particular flight has already been added to the latest alpha.

**Comment by IngoStramm** [comment]
Don't know if this was already fixed, but just in case, this is the error message:

Flight details: Garadar (0.29:0.62) to Altar of Sha'tar (0.81:0.77) (Horde) took 291 seconds.  This flight does not exist in the database.

**Comment by leatrix** [comment]
In 1.14.23.alpha.6 or higher for Classic Era/SoM, LTP supports multiple flight routes to the same destination (i.e. LTP will use the full flight route in the flight data rather than just the start and destination).  So if two people fly to the same destination via different routes, LTP will treat them as two separate flights with separate flight times.  The report window now shows the full route too so when you submit a report for a flight time, I will see the route that you took.

I will copy this change over to BCC alpha soon.  Supporting multiple flight routes is a big change so it does mean that some flight times submitted over the last few days are now invalid (since the flight route is unknown).  Please submit them again after installing this update when you see the report window again.

**Comment by leatrix** [comment]
And now 2.5.83.alpha.11 for BCC supports multiple routes too.

**Comment by leatrix** [comment]
Closing this now to avoid confusion.  LTP now includes support for the full flight path in the latest releases for BCC and Classic Era/SoM.
