### ISSUE TITLE
My InFlight Horde Timers

### ISSUE THREAD

**Issue by Tenies** [leatrix/leatrix-plus-bcc#89]
InFlight addon has a way to calculate the final timer if you know the in between flight timers.
Here are my own horde InFlight timers with every flying master unlocked.

>>{
InFlightDB = {
	["version"] = "classic",
	["global"] = {
		["Horde"] = {
			["Kargath"] = {
				["Stonard"] = 225,
			},
			["Bloodvenom Post"] = {
				["Zoram'gar Outpost"] = 137,
				["Emerald Sanctuary"] = 69,
			},
			["Moonglade"] = {
				["Zoram'gar Outpost"] = 252,
				["Emerald Sanctuary"] = 186,
			},
			["Ratchet"] = {
				["Brackenwall Village"] = 101,
				["Thunder Bluff"] = 175,
				["Orgrimmar"] = 101,
			},
			["Hellfire Peninsula"] = {
				["Garadar"] = 254,
				["Shattrath"] = 193,
				["Spinebreaker Ridge"] = 125,
				["Swamprat Post"] = 190,
				["Altar of Sha'tar"] = 333,
				["The Stormspire"] = 364,
				["Mok'Nathal Village"] = 261,
				["Zabra'jin"] = 271,
				["Thrallmar"] = 61,
				["Thunderlord Stronghold"] = 296,
				["Shadowmoon Village"] = 252,
				["Cosmowrench"] = 381,
				["Falcon Watch"] = 123,
				["Stonebreaker Hold"] = 188,
			},
			["Freewind Post"] = {
				["Mudsprocket"] = 69,
				["Brackenwall Village"] = 96,
			},
			["Shadowmoon Village"] = {
				["Garadar"] = 207,
				["Stonebreaker Hold"] = 74,
				["Shattrath"] = 126,
				["The Stormspire"] = 379,
				["Swamprat Post"] = 205,
				["Altar of Sha'tar"] = 84,
				["Falcon Watch"] = 203,
				["Sanctum of the Stars"] = 65,
			},
			["Flame Crest"] = {
				["Stonard"] = 192,
			},
			["Orgrimmar"] = {
				["Shadowprey Village"] = 373,
				["Ratchet"] = 108,
				["Everlook"] = 240,
				["Emerald Sanctuary"] = 168,
			},
			["Gadgetzan"] = {
				["Brackenwall Village"] = 194,
			},
			["Stonard"] = {
				["Kargath"] = 231,
				["Grom'gol"] = 179,
				["Booty Bay"] = 230,
			},
			["Tarren Mill"] = {
				["Flame Crest"] = 444,
			},
			["Grom'gol"] = {
				["Kargath"] = 247,
				["Stonard"] = 174,
			},
			["Mok'Nathal Village"] = {
				["Evergrove"] = 88,
				["Thunderlord Stronghold"] = 63,
				["Area 52"] = 57,
				["Cosmowrench"] = 122,
				["The Stormspire"] = 104,
				["Swamprat Post"] = 73,
			},
			["Splintertree Post"] = {
				["Bloodvenom Post"] = 164,
				["Sun Rock Retreat"] = 286,
				["Ratchet"] = 203,
				["Emerald Sanctuary"] = 85,
			},
			["Sanctum of the Stars"] = {
				["Stonebreaker Hold"] = 134,
				["Shadowmoon Village"] = 61,
			},
			["Crossroads"] = {
				["Moonglade"] = 375,
				["Orgrimmar"] = 116,
				["Emerald Sanctuary"] = 241,
				["Thunder Bluff"] = 107,
			},
			["Garadar"] = {
				["Evergrove"] = 203,
				["Stonebreaker Hold"] = 146,
				["Shattrath"] = 77,
				["Spinebreaker Ridge"] = 264,
				["Altar of Sha'tar"] = 291,
				["Area 52"] = 274,
				["Falcon Watch"] = 126,
				["Hellfire Peninsula"] = 269,
				["Cosmowrench"] = 339,
				["Swamprat Post"] = 156,
				["Thunderlord Stronghold"] = 178,
				["Thrallmar"] = 199,
				["Shadowmoon Village"] = 210,
				["Mok'Nathal Village"] = 226,
				["The Stormspire"] = 321,
				["Zabra'jin"] = 67,
			},
			["Light's Hope Chapel"] = {
				["Tranquillien"] = 118,
			},
			["Sun Rock Retreat"] = {
				["Zoram'gar Outpost"] = 121,
			},
			["Shadowprey Village"] = {
				["Zoram'gar Outpost"] = 320,
			},
			["Area 52"] = {
				["Evergrove"] = 81,
				["Shattrath"] = 223,
				["Thunderlord Stronghold"] = 108,
				["Mok'Nathal Village"] = 65,
				["Cosmowrench"] = 66,
				["The Stormspire"] = 49,
				["Thrallmar"] = 273,
			},
			["Mudsprocket"] = {
				["Brackenwall Village"] = 63,
				["Freewind Post"] = 72,
				["Ratchet"] = 150,
				["Orgrimmar"] = 245,
			},
			["Brackenwall Village"] = {
				["Ratchet"] = 89,
				["Freewind Post"] = 105,
				["Gadgetzan"] = 205,
				["Camp Taurajo"] = 50,
				["Mudsprocket"] = 63,
				["Cenarion Hold"] = 357,
				["Camp Mojache"] = 228,
			},
			["Silvermoon City"] = {
				["Tranquillien"] = 66,
			},
			["Zoram'gar Outpost"] = {
				["Bloodvenom Post"] = 138,
				["Sun Rock Retreat"] = 122,
				["Shadowprey Village"] = 264,
				["Emerald Sanctuary"] = 122,
				["Moonglade"] = 262,
			},
			["Thunderlord Stronghold"] = {
				["Evergrove"] = 26,
				["Garadar"] = 227,
				["Shattrath"] = 203,
				["Area 52"] = 97,
				["Swamprat Post"] = 116,
				["The Stormspire"] = 158,
				["Cosmowrench"] = 162,
				["Zabra'jin"] = 148,
				["Mok'Nathal Village"] = 56,
			},
			["Everlook"] = {
				["Orgrimmar"] = 243,
			},
			["The Stormspire"] = {
				["Stonebreaker Hold"] = 345,
				["Shattrath"] = 277,
				["Thunderlord Stronghold"] = 146,
				["Area 52"] = 54,
				["Cosmowrench"] = 69,
			},
			["Evergrove"] = {
				["Area 52"] = 78,
				["Mok'Nathal Village"] = 91,
				["Thunderlord Stronghold"] = 36,
			},
			["Booty Bay"] = {
				["Stonard"] = 241,
			},
			["Stonebreaker Hold"] = {
				["Evergrove"] = 266,
				["Garadar"] = 138,
				["Area 52"] = 261,
				["Hellfire Peninsula"] = 195,
				["Thunderlord Stronghold"] = 241,
				["Cosmowrench"] = 327,
				["The Stormspire"] = 309,
				["Shattrath"] = 56,
				["Spinebreaker Ridge"] = 190,
				["Altar of Sha'tar"] = 149,
				["Falcon Watch"] = 133,
				["Swamprat Post"] = 136,
				["Thrallmar"] = 125,
				["Shadowmoon Village"] = 68,
				["Mok'Nathal Village"] = 206,
				["Zabra'jin"] = 193,
				["Sanctum of the Stars"] = 133,
			},
			["Shattrath"] = {
				["Evergrove"] = 211,
				["Garadar"] = 82,
				["Area 52"] = 205,
				["Hellfire Peninsula"] = 219,
				["Thunderlord Stronghold"] = 185,
				["Shadowmoon Village"] = 133,
				["The Stormspire"] = 253,
				["Stonebreaker Hold"] = 69,
				["Spinebreaker Ridge"] = 215,
				["Swamprat Post"] = 80,
				["Cosmowrench"] = 271,
				["Falcon Watch"] = 77,
				["Thrallmar"] = 150,
				["Altar of Sha'tar"] = 214,
				["Mok'Nathal Village"] = 150,
				["Zabra'jin"] = 136,
				["Sanctum of the Stars"] = 197,
			},
			["Spinebreaker Ridge"] = {
				["Hellfire Peninsula"] = 133,
				["Cosmowrench"] = 389,
				["Falcon Watch"] = 129,
				["Thrallmar"] = 62,
			},
			["Falcon Watch"] = {
				["Evergrove"] = 200,
				["Garadar"] = 133,
				["Shattrath"] = 72,
				["Swamprat Post"] = 69,
				["Hellfire Peninsula"] = 143,
				["Thrallmar"] = 74,
				["Stonebreaker Hold"] = 140,
				["Mok'Nathal Village"] = 140,
				["Zabra'jin"] = 150,
				["Shadowmoon Village"] = 204,
			},
			["Swamprat Post"] = {
				["Evergrove"] = 132,
				["Stonebreaker Hold"] = 155,
				["Shattrath"] = 87,
				["Area 52"] = 126,
				["Hellfire Peninsula"] = 205,
				["Zabra'jin"] = 111,
				["Falcon Watch"] = 63,
				["Thrallmar"] = 136,
				["Cosmowrench"] = 192,
				["Mok'Nathal Village"] = 71,
				["The Stormspire"] = 174,
				["Thunderlord Stronghold"] = 106,
			},
			["Camp Taurajo"] = {
				["Brackenwall Village"] = 60,
			},
			["Cosmowrench"] = {
				["The Stormspire"] = 61,
				["Area 52"] = 65,
			},
			["Emerald Sanctuary"] = {
				["Brackenwall Village"] = 369,
				["Bloodvenom Post"] = 80,
				["Moonglade"] = 203,
				["Everlook"] = 225,
				["Valormok"] = 169,
				["Splintertree Post"] = 83,
				["Zoram'gar Outpost"] = 115,
			},
			["Altar of Sha'tar"] = {
				["Stonebreaker Hold"] = 139,
				["Shattrath"] = 192,
				["Thrallmar"] = 263,
				["Swamprat Post"] = 272,
				["Shadowmoon Village"] = 67,
				["Garadar"] = 273,
				["Hellfire Peninsula"] = 333,
			},
			["Tranquillien"] = {
				["Silvermoon City"] = 74,
				["Light's Hope Chapel"] = 117,
			},
			["Thrallmar"] = {
				["Garadar"] = 199,
				["Stonebreaker Hold"] = 128,
				["Shattrath"] = 138,
				["Spinebreaker Ridge"] = 66,
				["Falcon Watch"] = 68,
				["Swamprat Post"] = 135,
				["Zabra'jin"] = 217,
				["Hellfire Peninsula"] = 70,
			},
			["Cenarion Hold"] = {
				["Brackenwall Village"] = 333,
			},
			["Zabra'jin"] = {
				["Evergrove"] = 139,
				["Garadar"] = 81,
				["Shattrath"] = 151,
				["Spinebreaker Ridge"] = 285,
				["Area 52"] = 209,
				["Swamprat Post"] = 112,
				["Hellfire Peninsula"] = 290,
				["The Stormspire"] = 257,
				["Mok'Nathal Village"] = 168,
				["Thunderlord Stronghold"] = 113,
				["Thrallmar"] = 220,
				["Cosmowrench"] = 274,
				["Shadowmoon Village"] = 284,
				["Falcon Watch"] = 148,
				["Stonebreaker Hold"] = 219,
			},
			["Camp Mojache"] = {
				["Brackenwall Village"] = 203,
			},
		},
	}

**Comment by leatrix** [comment]
InFlight doesn't have accurate times for a lot of flights.  That includes not only flights that it's simply not aware of at all, but also flights that it is aware but have a different route path.  So if a character has different flight points unlocked to what InFlight is expecting, InFlight will get the flight time wrong.

So for flights that it's not aware of (or route variations of flights that it is aware of), InFlight guesses the flight time and shows an estimate instead of the actual flight time (you can see it's an estimate as the flight time will be prefixed with ~).

When you take the flight, InFlight shows the estimated time on the first run but it records the actual flight time when you land.  It then saves the actual time in your saved variables file and uses that flight time in future.  However, it seems to save the flight time account-wide so when you login to a character that doesn't have the same flight points unlocked, the flight time is going to be wrong.

So this is a mess and I don't want LTP to work this way.  Using estimated times and sharing saved variables files around is not what i want to achieve with the show flight times setting.

LTP shows an accurate flight time (if known), otherwise it shows the flight details in a report window after you land so that you can report the actual flight time (and it makes it very easy to report).  Shortly after receiving your report, the flight time will be added to the addon for everyone to use.  There is no need for showing estimated times and no need for saving times in the saved variables file.

LTP doesn't save flight times in the saved variables file because that file is personal to your account.  So recording the time in saved variables works for you but doesn't help anyone else.  So then you have a situation where you are sharing your saved variables file around and people have different saved variables files with different flight routes and the whole thing becomes a mess.  You also have incorrect flight times because the saved variables file assumes that you have certain flight points unlocked which your character (and the people you share the file with) may not have.

I think the way LTP approaches this is much better.  After all, there is a finite number of flights in Classic so why waste time with estimated times and saved variables.  Let's just have a complete list of all flights and be done with it, shall we?

I have added a lot of flight times to LTP myself in order to get LTP off to a good start with flight times.  Lots of people are reporting flight times via GitHub, CurseForge or email and I am adding them to the addon as I receive them (initially they are added in alpha but LTP is updated every week so if you update LTP using CurseForge App, you will always have the most up-to-date flight times automatically).  

The goal is to have LTP be aware of every flight time for every flight (regardless of flight route) and together we can achieve that.  Then there will be no need for estimated times or sharing saved variables files around.  And there will be no need for fixes and hacks to get the addon working for the latest game or expansion because LTP is always updated for every game and expansion.

So keep reporting your flight times from the LTP report window.  Press CTRL/C then paste into an email to flight@leatrix.com (or GitHub or CurseForge message).  Done.  Within a very short time, everyone who uses LTP will have your reported flight time automatically, distributed by CurseForge App.

I can't use InFlight saved variables data because of reasons I already explained.

**Comment by Tenies** [comment]
As i understand LTP has much more accurate timers specially when u missing flying paths, that's why i noted that i have every flying path unlocked. Sadly i don't have the time lately so i can't contribute at the time being, so i gave you my InFlight timers with the hope they can help. A made 99% of those in TBC era (Crossroads to Moonglade 375sec was the only one i made at Classic Era based on my backups) and here i should note that some flying timers are different than Classic era. Blizzard had shorten a lot of Azeroth's timers when they released TBC. Some are just few secs, some are minutes faster. E.g. Ratchet to Brackenwall Village takes 231s in Classic era and only 101s in TBC era. You will see few of those "fixes" at my list above.

**Comment by leatrix** [comment]
The reason LTP is more accurate when you log into a character that has missing flight points is that LTP uses route strings rather than simple start and destination points.  A route string contains the start and destination plus every hop in between.

For example, if you fly from Stormwind to Thorium Point, you can go via Morgan's Vigil or Ironforge.  Which route you are taken depends on which flight points you have unlocked.  Flying via Morgan's Vigil takes 247 seconds while flying via Ironforge takes 291 seconds.

So, LTP accounts for both routes using these route strings:
["0.43:0.67:0.58:0.65:0.51:0.57"] = 247
["0.43:0.67:0.51:0.49:0.51:0.57"] = 291

(the numbers are the start, destination and hops in between).

This gives you specific times for each route.  If LTP only used start and destination times as some other flight time addons do, the time would be accurate for one route only, not the other.

InFlight only uses start and destination times so I can't add InFlight data to LTP - it's too limited.  LTP needs the full route string which is shown to you in the report window after you land from a flight route that LTP isn't aware of because the route string will tell LTP exactly which route you took to get from start to destination.

So when you see LTP show the report window, press CTRL/C (no need to click or drag anything) and paste it into a ticket here, or a message to leatrix on CurseForge or an email to flight@leatrix.com.  Lots of people are doing exactly that and everyone gets the new flight times automatically when they update LTP.

LTP knows most of the flights in BCC and Classic now so keep reporting until it knows them all and report windows will no longer show up.
