### ISSUE TITLE
Flight timer: use existing bars

### ISSUE THREAD

**Issue by godsyn** [leatrix/leatrix-plus-bcc#92]
Like inflight (a resource if you want old world flight times), please use the existing cast bars for flight times.
Add the text "Duration: " before the flight time on the flight choice map.
Remove the preceding 0 from flight times less than 10 minutes.
Use "-:--" or similar to signify unknown flight times.

![image](https://user-images.githubusercontent.com/508678/149622081-7e7f7d88-cd94-4c3d-851d-45cc61940209.png)
I'd love to (finally) replace inflight with this addon.

![image](https://user-images.githubusercontent.com/508678/149622106-8f3d88a6-2b4e-48f0-b446-be216e4065bb.png)
![image](https://user-images.githubusercontent.com/508678/149622112-18a750af-f523-4a7d-a1a2-b4b93ba5bae3.png)

**Comment by leatrix** [comment]
In the latest alpha, flight point tooltips show the word 'Duration' for both known and unknown flight times.  -:-- will be used to show unknown flight times, however, the goal of Leatrix Plus is to know every flight time so that you don't need to share times or keep them in saved variables.  Flight times less than 10 minutes will no longer show a 0 prefix.  Progress bar will stay as it is for now but I could add a configuration panel for scale and positon.

[This post](https://github.com/leatrix/leatrix-plus-bcc/issues/89#issuecomment-1012361179) explains why InFlight data can't be imported to Leatrix Plus.  The data is too limited.  Leatrix Plus needs the full flight string so that it can accommodate multiple routes (for characters that don't have all the flight points unlocked).  InFlight doesn't cater for multiple routes as it only uses the start and destination so the data from InFlight isn't enough.

Leatrix Plus now contains the flight times for nearly 2000 flights for BCC and nearly 1000 for Classic Era and more are being added daily.  No need to share saved variables - everyone will get the updated flight times every week when they update Leatrix Plus.

**Comment by godsyn** [comment]
The timers on the map look nice. Thanks.
Wish I knew enough LUA to hook into other addon's bars.
